### ISSUE TITLE
typescript supprt

### ISSUE THREAD

**Issue by rr-kalbeck** [penx/css-hyperclick#1]
doesn't work in .ts or .tsx files

**Comment by penx** [comment]
@rr-kalbeck 

The intention of this package is to add functionality to CSS or CSS-like files (SCSS, Sass, LESS,  etc), rather than JS-like files. I'm not sure it makes sense to add support for TypeScript, unless you could provide an example of how you see this working?

It makes more sense to me that TypeScript support would be something that should be supported by [js-hyperlick](https://github.com/AsaAyers/js-hyperclick) - in fact maybe it already supports this?

**Comment by penx** [comment]
In fact the package atom-typescript should already provide this: https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/hyperclickProvider.ts

**Comment by rr-kalbeck** [comment]
i'm using webpack to import css, i can click a ts or js import to go to the file but not a css file. perhaps this is an issue for atom-typescript?

**Comment by penx** [comment]
Yes I think this is something to raise with atom-typescript - I can see you have raised this already at https://github.com/TypeStrong/atom-typescript/issues/1365
